---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: crawler
        env:
          - name: MONGO
            value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
          - name: RMQ_HOST
            value: {{ .Values.rabbitMQHost | default (printf "%s-rabbitmq" .Release.Name) }}
          - name: RMQ_QUEUE
            value: {{ .Values.rmq_queue | default (printf "%s-rmqqueue" .Release.Name) }}
          - name: RMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-crawler" .Release.Name }}
                key: rabbitmq_user
          - name: RMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-crawler" .Release.Name }}
                key: rabbitmq_password
          - name: URL
            value: {{ .Values.URL }}
          - name: EXCLUDE_URLS
            value: {{ .Values.excluded_urls }}
