apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-crawler" .Release.Name }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
type: Opaque
stringData:
  rabbitmq_user: {{ .Values.env.rabbitmq_user }}
  rabbitmq_password: {{ .Values.env.rabbitmq_password }}
