---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: search-engine
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-engine
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: search-engine
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: ui
        env:
          - name: MONGO
            value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
