dependencies:
  - name: ui
    version: "1.0.0"
    repository: "file://../search-engine-ui"
  - name: crawler
    version: "1.0.0"
    repository: "file://../search-engine-crawler"
  - name: rabbitmq
    version: "4.3.0"
    repository: "file://../rabbitmq"
  - name: mongodb
    version: "5.5.0"
    repository: "file://../mongodb"
